### ISSUE TITLE
Keep getting login blocked (https://web.facebook.com/checkpoint/block/)

### ISSUE THREAD

**Issue by RobbiNespu** [marcelja/facebook-delete#28]
Hi there, I found your tool and I able to use to deleted some data
```
> Wed 08 Sep 2021 02:54:41 PM +08  
robbi@debian: pts/1: /home/robbi/RM-RF 
└─ $ ./deleter-linux --rateLimit 5000
Waiting 5000 ms before search and delete requests.
Logged in with user: XX XX (profile ID: XXXXXXX)
? Which years 2021
? Which months Jan
? Which categories All App Activity, Comments, Event Invitations, Event Responses, Group Posts and Comments, Group Reactions, Instagram Photos and Videos, Likes and Reactions, Others' Posts To Your Timeline, Photos and Videos, Posts, Posts You're Tagged In, Search History, Spotify, Your Events

Searching elements from 2021:
Jan ... ... ... ... ... ... ... ... ... ... ...   Elements found:       200
Deleting elements from 2021:
200 / 200 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1 p/s 4m25s
Group Reactions: 1 deleted
Likes and Reactions: 4 deleted
Search History: 195 deleted
Total: 200 deleted
```

It my trial run and I want to delete by per month.. but when I try for second round, It doesnt work anymore. I keep getting blocked and asked to change password everytime I execute. 

I try deleting the cookies and still get same thing.. it has been two day.

```
> Thu 09 Sep 2021 03:31:04 PM +08  
robbi@debian: pts/2: /home/robbi/RM-RF 
└─ $ ./deleter-linux --rateLimit 10000
Waiting 10000 ms before search and delete requests.
? Please type your email xx@hotmail.com
? Please type your password *********************
Attempting Login...
panic: Failed to login

goroutine 1 [running]:
main.newFbLogin(0xc00018aea0, 0xc000182008)
        /Users/marcel/pr/facebook-delete/deleter.go:118 +0xde
main.main()
        /Users/marcel/pr/facebook-delete/deleter.go:522 +0x1f3
```

I wonder and guesss, it maybe cause by user agent signature by this tool

This is my browser user agent
```
Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
```

When I use web browser (after change new pass and each time before I exec the tool), I able to use fb. So after 1h-3h, I come back and use the tool.. my account will be blocked and need to change pass again.

Let me know if I need to add more information

**Comment by marcelja** [comment]
I don't know how facebook detects this. For me, it always worked fine. User agent could definitely be something that's related. Maybe we could set a user agent in our client
