### ISSUE TITLE
deleter-windows.exe closes immediately after launch

### ISSUE THREAD

**Issue by clouser123** [marcelja/facebook-delete#29]
I ran the Windows executable and it all went fine when I tested on one of the accounts. 
Once I tried running again, the program automatically closes without prompting for any login.

**Comment by ryanisayori** [comment]
Same thing happened to me, it closed automatically after a while, then my facebook page refreshed to request me to verify if I am the owner and changed my password.

**Comment by tigertime2019** [comment]
Had the same issue. Will accept email and password, execution output attached. 
![FB deleter](https://user-images.githubusercontent.com/56378404/136911258-3906d8ee-e81b-47ec-8ec7-893ced0f0f21.png)

**Comment by Lod3** [comment]
I have had the same thing with multi factor authentication enabled. 
After reopening the script it will ask for email and password again after that you should be logged in.

**Comment by tigertime2019** [comment]
Hey Lod3 - tried again per your instructions and got the same crash as I had experienced previously. 
Might try it on a Linux VM when I get around to it.

**Comment by Akor3** [comment]
I get the same issue, MFA disabled, just crashes right after running:
![image](https://user-images.githubusercontent.com/92418239/137064552-7be99e46-8336-4100-bf4c-fe36f8aa6179.png)

**Comment by Lod3** [comment]
Yeah it worked but now it does not start again and gives me this:

`
┌──(ori㉿Tonk)-[~/facebook-delete]                                                                                      └─$ go run deleter.go                                                                                                   panic: runtime error: index out of range [1] with length 1                                                                                                                                                                                      goroutine 1 [running]:                                                                                                  main.(*fbLogin).StoreProfileID(0xc0000d0440, 0xc0004da000, 0x1976)                                                              /home/ori/facebook-delete/deleter.go:178 +0x108                                                                 main.(*fbLogin).IsLoggedIn(0xc0000d0440, 0xc0000d0440)                                                                          /home/ori/facebook-delete/deleter.go:172 +0xb7                                                                  main.newFbLogin(0xc0000a1080, 0xc0000a01f0)                                                                                     /home/ori/facebook-delete/deleter.go:113 +0x55                                                                  main.main()                                                                                                                     /home/ori/facebook-delete/deleter.go:522 +0x1f3                                                                 exit status 2  
`
