### ISSUE TITLE
index out of range [1] with length 1

### ISSUE THREAD

**Issue by chpstx** [marcelja/facebook-delete#38]
I recently stumbled on this error prompt.
It might be due to fb forcing me to change password.

I tried modifying debug_login.sh to input my new creds, but I can't make it work. (I don't/can't code)

```
PS C:\Users\jaspe\Documents\GitHub\facebook-delete> go run deleter.go -rateLimit 7000
Waiting 7000 ms before search and delete requests.
panic: runtime error: index out of range [1] with length 1


goroutine 1 [running]:
main.(*fbLogin).StoreProfileID(0xc000064400, {0xc0000fe000, 0xf232ff})
        C:/Users/jaspe/Documents/GitHub/facebook-delete/deleter.go:178 +0xbe
main.(*fbLogin).IsLoggedIn(0xc000064400)
        C:/Users/jaspe/Documents/GitHub/facebook-delete/deleter.go:172 +0x75
main.newFbLogin(0xc000056fb0)
        C:/Users/jaspe/Documents/GitHub/facebook-delete/deleter.go:113 +0x53
main.main()
        C:/Users/jaspe/Documents/GitHub/facebook-delete/deleter.go:522 +0x289
exit status 2
PS C:\Users\jaspe\Documents\GitHub\facebook-delete>
```

**Comment by jamesbretz** [comment]
I was able to delete the hidden file ".go-cookies" from my OSX user folder and start the login process again after getting this error.
