### ISSUE TITLE
Error on MacOS M1 (ARM arch)

### ISSUE THREAD

**Issue by Sigri44** [marcelja/facebook-delete#46]
I see "Marcel" user on binary launch : 

```bash
Downloads % ./deleter-macos
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12cd6e5]

goroutine 1 [running]:
main.(*requester).Request(0xc000097140, {0x136402e, 0x100cc67})
	/Users/marcel/pr/facebook-delete/deleter.go:67 +0x65
main.(*fbLogin).IsLoggedIn(0xc0000b0480)
	/Users/marcel/pr/facebook-delete/deleter.go:168 +0x34
main.newFbLogin(0xc000097140)
	/Users/marcel/pr/facebook-delete/deleter.go:113 +0x53
main.main()
	/Users/marcel/pr/facebook-delete/deleter.go:522 +0x289


Downloads % ./deleter-macos-arm64 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10485e384]

goroutine 1 [running]:
main.(*requester).Request(0x14000113140, {0x10486fcd0, 0x23})
	/Users/marcel/pr/facebook-delete/deleter.go:67 +0x84
main.(*fbLogin).IsLoggedIn(0x14000140440)
	/Users/marcel/pr/facebook-delete/deleter.go:168 +0x40
main.newFbLogin(0x14000113140)
	/Users/marcel/pr/facebook-delete/deleter.go:113 +0x60
main.main()
	/Users/marcel/pr/facebook-delete/deleter.go:522 +0x32c
```

**Comment by marcelja** [comment]
It looks like the HTTP requests fail. Do you have something installed that blocks internet traffic for some applications?

**Comment by Sigri44** [comment]
> 

Hum yes i have Pi-Hole to have a fake-dns, but i can whitelist domain/wildcard.

**Comment by marcelja** [comment]
Does it work when you visit https://mbasic.facebook.com/ in a browser?

**Comment by Sigri44** [comment]
> Does it work when you visit https://mbasic.facebook.com/ in a browser?

Nop, GAFA tracking is all blocked ahah ! Why need this ?

**Comment by Sigri44** [comment]
Fixed ! Amazing, thank you so much !! Have a nice day
