### ISSUE TITLE
Can't start login on macOS 12.3.1

### ISSUE THREAD

**Issue by roeniss** [marcelja/facebook-delete#53]
I downloaded the latest binary file, but it fails to start:

```sh
❯❯❯ rm -rf /Users/roeniss/.go-cookies # actually, it doesn't exist
❯❯❯ sudo ./deleter-macos # I also tried deleter-macos-arm64
Waiting 100 ms before search and delete requests.
panic: Unable to parse profile information from cookies. Try manually deleting the cookie file stored in /Users/roeniss/.go-cookies

goroutine 1 [running]:
main.(*fbLogin).StoreProfileID(0xc00007e540, {0xc000420000, 0x15d6})
        github.com/marcelja/facebook-delete/deleter.go:186 +0x159
main.(*fbLogin).IsLoggedIn(0xc00007e540)
        github.com/marcelja/facebook-delete/deleter.go:177 +0x75
main.newFbLogin(0xc000011180)
        github.com/marcelja/facebook-delete/deleter.go:118 +0x53
main.main()
        github.com/marcelja/facebook-delete/deleter.go:548 +0x38c
```

The `~/.go-cookies` file is never created. Is this known issue?

**Comment by marcelja** [comment]
I don't think you should use sudo.

**Comment by resurtm** [comment]
@marcelja, @roeniss, FYI: https://www.reddit.com/r/facebook/comments/1g5tsf4/mbasic_is_going_away_on_28_october_2024_whats_the/
